# Site settings
title: Ana Pereira
subtitle: Psicologia clínica
email:
description: >-
 Psicóloga clínica.
minimal_mistakes_skin: default
search: false
url: https://anapereirapsicologia.pt

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-7LPPTQHF4T"

author:
  name   : "Ana Pereira"
  avatar : "/assets/images/profile.png"
  bio    : "Psicologia clínica"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/"
      
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false

after_footer_scripts:
  - /assets/js/after-footer.js
